version: "3.7"
services:
 backend:
  build: Spring
  image: piyushb9/osmappserver
  networks:
   - node-rest
  expose:
   - 8080
 frontend:
  build:
   context: Node
  image: piyushb9/osmwebserver
  ports:
   - 8080:8080
  networks:
   - node-rest
  depends_on:
   - backend
networks:
 node-rest: {}
